import Head from "next/head"

export default function Contact(){
    return(
        <>
      <Head>
        <title>Lumine Films | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Estamos en Contact</h1>
    </>
    )
}