import Head from 'next/head'


export default function Home({results}) {
  const data = results.results
  const API_URL_POSTER = "https://image.tmdb.org/t/p/w500"
  const API_URL_BANNER = "https://image.tmdb.org/t/p/original"

  console.log(data);

  // const stylesHome = {
  //   width: "100vw",
  //   backgroundImage: `url(${API_URL_BANNER}${data[0].backdrop_path})`,
  //   backgroundRepeat: "no-repeat",
  //   backgroundSize: "contain",
  // }
  return (
    <>
      <Head>
        <title>Lumine Films | Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Estamos en Home</h1>

      <main>
        {data.map(movie =>{
          return(
            <article className='card' key={movie.id}>
              {/* <h2>{movie.title}</h2> */}
              <img src={`${API_URL_POSTER}${movie.poster_path}`} alt=''></img>
            </article>
          )
        })}
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  
  const API_URL = "https://api.themoviedb.org/3";
  const API_KEY = "597de7cc5d76799b861b35385e56a10a";

  const results = await fetch(`${API_URL}/movie/popular?api_key=${API_KEY}&language=es&page=1`).then(res => res.json())
  // const results = await response.json()

  return {
    props: {
      results
    }, // will be passed to the page component as props
  }
}
